apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 834239361433.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 834239361433.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 08fb6ec2
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
